# -*- coding: utf-8 -*-
"""case_study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bFpvy-sHP-4T7tibinYO-o-MGzXU3ns

**Autor: Nikolay Kutukov**

#Přehled datasetu
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
!pip install -q dython
from dython.nominal import associations
data = pd.read_csv('fotbal_prestupy_2000_2019.csv')
csob_blue = "#24B7F1"
csob_dark_blue = "#003869"
mpl.rcParams['font.family'] = 'serif'
data.head()

"""Kontrola chybějících hodnot, jenom sloupec odhadovaná hodnota obsahuje chybějící hodnoty"""

data.isna().sum()

"""Kontrola typu proměnných, "Odhadovaná hodnota" by měla být stejnecho typu jako "Přestupová částka", ale protože obsahuje NA nesmí být typu int"""

data.info()

"""Popis numerických sloupců. Věk nula nedává smysl měli bychom to nahradit; rozsah hodnot ve sloupcích 'Odhadovaná hodnota' a 'Přestupová částka' je obrovský, má smysl použit logaritmickou škálu pro vizualizaci."""

data.describe()

"""V datasetu nejsou žádné duplicity"""

data.drop_duplicates().shape[0] ==  data.shape[0]

"""Složení původních a nových týmů a lig je velmi odlišné"""

print(f"Počet různých lig, které hráči opustili: {len(data['Původní liga'].unique())}")
print(f"Počet různých lig, do kterých hráči přestoupili: {len(data['Nová  Liga'].unique())}\n")
print(f"Počet různých týmů, které hráči opustili: {len(data['Původní tým'].unique())}")
print(f"Počet různých týmů, do kterých hráči přestoupili: {len(data['Nový tým'].unique())}")

"""#Čištění a transformace dat"""

data_cl = data.copy() #vytvořime novou proměnnou pro čištění dat

data_cl[data_cl['Věk']<16] #Marzouqovi Al-Otaibimu bylo 24 let v roce 2000

data_cl.loc[data_cl['Jméno']=='Marzouq Al-Otaibi', 'Věk']=24

"""Hodnoty ve sloupci "A" jsou špatně čitelné, změňme škalu na miliony"""

data_cl.head(1)

data_cl['Odhadovaná hodnota'] /= 10**6
data_cl['Přestupová částka'] /= 10**6
pd.concat([data.head(1), data_cl.head(1)])

"""Hodnoty "Forward", "Sweeper", "Defender" a "Midfielder" mají příliš malé počty, tato pozorování necháme v datovém souboru, ale vyloučíme je pro analýzu podle pozic"""

data_cl['Pozice'].value_counts()

data[data['Pozice'].isin(['Forward', 'Sweeper', 'Defender', 'Midfielder'])]

"""#Vizualizace

Z korelační matice vidíme, že hodnota přestupové částky silně souvisí se samotným hráčem, týmem, za který hraje, a sezónou, ve které se přestup uskutečnil. V menší míře s ligou, která úzce souvisí s týmem, a pozicí hráče. Věk hráče nemá na velikost přestupu žádný vliv.
"""

#@title Korelační matice

complete_correlation= associations(data, filename= 'complete_correlation.png', figsize=(8,8))
df_complete_corr=complete_correlation['corr']

#@title Odhad je často menší než skutečná částka, v průměru o 11%.
import matplotlib.ticker as ticker
#function to change the format of values on X axis from powers of 10 to general
def format_fn(tick_val, _):
        return f"{int(tick_val)}"

avg_dif = round(((data['Přestupová částka'] - data['Odhadovaná hodnota'])/data['Přestupová částka']).mean() * 100, 2)
transfer_val = data_cl['Přestupová částka']
pred_val = data_cl['Odhadovaná hodnota']
avg_dif = round(((data['Přestupová částka'] - data['Odhadovaná hodnota'])/data['Přestupová částka']).mean() * 100, 2)
bins = np.logspace(np.log10(min(transfer_val)), np.log10(max(transfer_val)), 50)


plt.hist(transfer_val, bins=bins, alpha=0.7, color=csob_blue, label='Skutečná hodnota')
plt.hist(pred_val, bins=bins, alpha=0.7, color=csob_dark_blue, label='Odhadovaná hodnota')
plt.text(29,290, "Průměrný rozdíl: " + str(avg_dif) + "%")
plt.xscale('log')
plt.gca().xaxis.set_major_formatter(ticker.FuncFormatter(format_fn))
plt.title('Rozdělění Přestupových Částek')
plt.xlabel('Přestupová částka (mil. $)')
plt.ylabel('Počet')
plt.legend()
plt.show()

#@title Věkové rozdělení je velmi podobné normalnímu rozdělení.
from scipy.stats import norm
age_norm = np.random.normal(data_cl['Věk'].mean(),data_cl['Věk'].std(), len(data_cl['Věk']))
plt.hist(data_cl['Věk'], bins = data_cl['Věk'].nunique(), density = True, color = csob_blue, edgecolor='white')

mu, std = norm.fit(data_cl['Věk'])
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, len(data_cl['Věk']))
p = norm.pdf(x, mu, std)
plt.plot(x, p, color = "#E86A92", label="Normální rozdělení")
plt.xticks(data_cl['Věk'].unique())
plt.title('Rozdělení podle věku')
plt.ylabel('Pravděpodobnost')
plt.legend()
plt.show()

"""###Pozice

Pro analyzu pozic budou pozice Midfielder, Defender, Forward a Sweeper vyloučený.
"""

data_pos = data_cl.groupby(by='Pozice').mean(numeric_only=True).sort_values(by='Přestupová částka', ascending= True)
data_pos

#@title Hráči na útočné pozici jsou v průměru hodnoceni mnohem více než ostatní.
data_pos_cl = data_pos[~data_pos.index.isin(['Forward', 'Sweeper', 'Defender', 'Midfielder'])]
plt.barh(y = data_pos_cl.index, width = data_pos_cl['Přestupová částka'], color=csob_blue, alpha=0.7, label='Skutečna hodnota')
plt.barh(y = data_pos_cl.index, width = data_pos_cl['Odhadovaná hodnota'], color=csob_dark_blue, alpha=0.7, label='Odhadovaná hodnota')
plt.xlabel('Přestupová částka (mil. $)')
plt.title('Průměrná přestupní částka podle pozice hráče')
plt.legend()
plt.show()

#@title Pokud se podíváme na 50 nejdražších přestupů je rozdíl v ceně útočících hráčů ještě výraznější. Hráči na obranných pozicích jsou v první padesátce zastoupeni mnohem méně.
data_pos_top = data_cl.nlargest(50, 'Přestupová částka').groupby(by='Pozice').mean(numeric_only=True).sort_values(by='Přestupová částka', ascending= True)
pos_counts = data_cl.nlargest(50, 'Přestupová částka')['Pozice'].value_counts()
data_pos_top = pd.merge(data_pos_top, pos_counts, left_index=True, right_index=True)
plt.figure(figsize=(8,6))
plt.barh(y = data_pos_top.index, width = data_pos_top['Přestupová částka'], color=csob_blue, alpha=0.6, label='Skutečna hodnota')
plt.barh(y = data_pos_top.index, width = data_pos_top['Odhadovaná hodnota'], color=csob_dark_blue, alpha=0.6, label='Odhadovaná hodnota')
plt.xlabel('Přestupová částka (mil. $)')
plt.title('Průměrná přestupní částka z 50 nejdrazších přestupů podle pozice')
plt.legend(loc='lower right')
for index, value in enumerate(data_pos_top['Přestupová částka']):
    plt.text(2, index,
             str(round(data_pos_top['Pozice'].iloc[index]*100/50)) + "% z top 50",
             va='center', color = 'white', fontsize=11)
plt.show()

"""##Týmy"""

#@title Athletic Bilbao je velmi úspěšný klub se silnými hráči, ale nedělá velké přestupy, protože v tomto klubu mohou hrát pouze Baskové.
data_tt = data_cl.groupby(by='Nový tým').mean(numeric_only=True).sort_values(by='Přestupová částka', ascending=True)
data_tf = data_cl.groupby(by='Původní tým').mean(numeric_only=True).sort_values(by='Přestupová částka', ascending=True)

plt.figure(figsize=(7,5))
plt.barh(y = data_tf.tail(10).index, width = data_tf.tail(10)['Přestupová částka'], color = csob_dark_blue)
plt.axvline(data_cl['Přestupová částka'].mean(), color = '#E86A92', alpha = 0.9, label = 'Průměrný přestup')
plt.xlabel('Přestupová částka (mil. $)')
plt.legend(loc='lower right')
plt.title('10 původních týmů s nejvyšší průměrnou přestupovou částkou')
plt.show()

plt.figure(figsize=(7,5))
plt.barh(y = data_tt.tail(10).index, width = data_tt.tail(10)['Přestupová částka'], color = csob_blue)
plt.axvline(data_cl['Přestupová částka'].mean(), color = '#E86A92', alpha = 0.9, label = 'Průměrný přestup')
plt.xlabel('Přestupová částka (mil. $)')
plt.legend(loc='lower right')
plt.title('10 nových týmů s nejvyšší průměrnou přestupovou částkou')
plt.show()

#@title 10 týmů, které zaplatily nejvíce za nové hráče. Seznam se skládá výhradně z klubů západní Evropy.
data_tt2 = data_cl.groupby(by='Nový tým').sum(numeric_only=True).sort_values(by='Přestupová částka', ascending=True)

plt.figure(figsize=(7,5))
plt.barh(y = data_tt2.tail(10).index, width = data_tt2.tail(10)['Přestupová částka'], color = csob_blue)
plt.xlabel('Přestupová částka (mil. $)')
plt.title('10 týmů, které zaplatily nejvíce za nové hráče')
plt.show()

"""Rozdělme týmy a ligy na "Top" a "Low".

"Top" jsou ligy a týmy, do kterých přestoupil aspoň jeden hráč, a "Low" ligy a týmy, do kterých žádný hráč nepřestoupil.
"""

#@title Porovnejme, jak se liší cena přestupu, pokud hráč pochází z "top" ligy nebo týmu a pokud pochází z "low" ligy nebo týmu.

dif_teams = [league not in data_cl['Nový tým'].unique() for league in data_cl['Původní tým'].unique()]
low_teams = data_cl['Původní tým'].unique()[dif_teams]
top_teams =  data_cl['Nový tým'].unique()
top_teams_avg = data_cl[data_cl['Původní tým'].isin(top_teams)]['Přestupová částka'].mean()
low_teams_avg = data_cl[data_cl['Původní tým'].isin(low_teams)]['Přestupová částka'].mean()

dif_leagues = [league not in data_cl['Nová  Liga'].unique() for league in data_cl['Původní liga'].unique()]
low_leagues = data_cl['Původní liga'].unique()[dif_leagues]
top_leagues =  data_cl['Nová  Liga'].unique()
top_leagues_avg = data_cl[data_cl['Původní liga'].isin(top_leagues)]['Přestupová částka'].mean()
low_leagues_avg = data_cl[data_cl['Původní liga'].isin(low_leagues)]['Přestupová částka'].mean()

values = [top_leagues_avg, low_leagues_avg, top_teams_avg, low_teams_avg]
labels = ['"Top" ligy', '"Low" ligy', '"Top" týmy', '"Low" týmy']
colors = [csob_dark_blue, csob_blue, csob_dark_blue, csob_blue]
plt.figure(figsize=(7,6))
plt.axhline(data_cl['Přestupová částka'].mean(), color = '#E86A92', alpha = 0.9, label = 'Průměrný přestup')
plt.bar(height = values, x = labels, color = colors)
plt.title('Průměrná částka pro hráče pocházející z "Top"/"Low" ligy a týmy')
plt.ylabel('Přestupová částka (mil. $)')
plt.legend(loc='upper right')
plt.show()

"""##Hráče

V datasetu jsou hráče se stejnými křestními jmény, nechame jenom jména, které obsahuji aspoň 2 slova, aby spravně spočitat počet transferu pro každého hráče
"""

first_and_last = data_cl['Jméno'].apply(lambda x: len(str(x).split())) > 1
filtered_df = data_cl[first_and_last]

#@title Podívejme se na 5 hráčů s největším počtem přestupů, můžeme konstatovat, že více přestupů neznamená více peněz.
from matplotlib.colors import LinearSegmentedColormap
most_transfers = filtered_df.groupby('Jméno').agg({'Nový tým':'count', 'Přestupová částka':'sum'}).sort_values(by='Nový tým', ascending=True).tail()

colors = [csob_blue, csob_dark_blue]
colormap = LinearSegmentedColormap.from_list("custom_blue", colors, N=100)
values = most_transfers['Přestupová částka']
normalized_values = (values - min(values)+ 10) / (max(values) - min(values))
plt.figure(figsize=(9,5))
plt.barh(y=most_transfers.index, width = most_transfers['Nový tým'], color=colormap(normalized_values))
plt.title('Hráči s největším počtem přestupů')
plt.xlabel('Počet přestupů')
for index, value in enumerate(most_transfers['Nový tým']):
    plt.text(1, index,
             'Suma částek: ' + str(most_transfers['Přestupová částka'].iloc[index]) + ' millionů $',
             va='center', color = 'white', fontsize=10)

sm = plt.cm.ScalarMappable(cmap=colormap, norm=plt.Normalize(vmin=min(values), vmax=max(values)))
cbar = plt.colorbar(sm)
cbar.set_label('Suma přestupových částek (mil. $)')

plt.show()

"""##Sezóna"""

#@title Graf ukazuje dynamiku průměrných hodnot fotbalových přestupů, míra růstu přestupových cen zní vyšší než inflace, možná fotbalisté nejsou špatnou investicí.
transfers_time_mean = data_cl.groupby(by='Sezóna').mean(numeric_only=True)
transfers_time_max = data_cl.groupby(by='Sezóna').max(numeric_only=True)
transfers_time_mean.index = transfers_time_mean.index.to_series().apply(lambda x: str(x)[:4])
transfers_time_max.index = transfers_time_mean.index.to_series().apply(lambda x: str(x)[:4])

plt.figure(figsize=(10, 5))
plt.plot(transfers_time_mean['Přestupová částka'])
plt.grid()
plt.ylabel('Přestupová částka (mil. $)')
plt.title('Průměrný přestupní částka v různých sezónach')
plt.show()

#@title Velikost maximálního přestupu obecně odpovídá vývoji průměrných přestupů.
plt.figure(figsize=(10, 5))
plt.plot(transfers_time_max['Přestupová částka'])
plt.grid()
plt.ylabel('Přestupová částka (mil. $)')
plt.title('Největší přestupní částka v různých sezónach')
plt.show()

"""##Obecné charakteristiky"""

#@title Tento graf poskytuje přehled deseti nejdražších přestupů do sezóny 2018-2019
top_transfers = data_cl.sort_values(by='Přestupová částka', ascending=False).head(10)
top_transfers = top_transfers.sort_values(by='Přestupová částka')
top_transfers['Jméno_unique'] = top_transfers['Jméno'] + ' (' + top_transfers['Sezóna'] + ')'
plt.figure(figsize=(12, 8))

plt.barh(y = top_transfers['Jméno_unique'], width=top_transfers['Přestupová částka'], color = csob_dark_blue, zorder=2)
plt.xlabel('Přestupová částka (mil. $)', fontsize=12)
fixed_position = min(top_transfers['Přestupová částka']) * 0.05
for index, value in enumerate(top_transfers['Přestupová částka']):
    plt.text(fixed_position, index,
             str(top_transfers['Původní tým'].iloc[index]) + ' → ' + str(top_transfers['Nový tým'].iloc[index]),
             va='center', color = 'white', fontsize=11)
for index, value in enumerate(top_transfers['Přestupová částka']):
    plt.text(value - value*0.02, index, str(int(value)) + ' millionů $', va='center', ha='right',
             color='white', fontsize=11)
plt.title('10 nejdražších fotbalových přestupů', fontsize = 14)
plt.grid(axis= 'x', zorder = 0)
plt.show()

#@title Podívejme se na údaje o přestupech v sezóně 2017-2018, kdy došlo k nejdražšímu přestupu v historii.
season_data = data_cl[data_cl['Sezóna'] == '2017-2018']

most_expensive_transfer = season_data.loc[season_data['Přestupová částka'].idxmax()]

total_fee_most_expensive = most_expensive_transfer['Přestupová částka']
total_fee_others = season_data['Přestupová částka'].sum() - total_fee_most_expensive

import matplotlib.pyplot as plt

top_10_transfers = season_data.nlargest(10, 'Přestupová částka')

total_next_top_9 = top_10_transfers['Přestupová částka'].sum() - total_fee_most_expensive

total_fee_outside_top_10 = season_data['Přestupová částka'].sum() - top_10_transfers['Přestupová částka'].sum()

labels = ['Neymar', 'Jiné z 10 nejdrazších', 'Ostatní hráče']
sizes = [total_fee_most_expensive, total_next_top_9, total_fee_outside_top_10]
colors=['#FF6100', '#04A0D3', '#92B522']

plt.figure(figsize=(6, 6))
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140)
plt.title('Podíl přestupních částek v sezóně 2017-2018')
plt.show()

#@title Porovnejme Neymarův přestup s průměrným a "nejlevnějším" přestupem v sezóně 2017-2018, abychom si uvědomili, jak drahý vyšel pro klub PSG. Je 11krát dražší než průměrný přestup v sezoně a 31krát dražší než ten "nejlevnější".
average_transfer_fee = season_data['Přestupová částka'].mean()

cheapest_transfer_fee = season_data['Přestupová částka'].min()

categories = ['Neymar', 'Průměr', '"Nejlevnější"']
values = [total_fee_most_expensive, average_transfer_fee, cheapest_transfer_fee]

plt.figure(figsize=(8, 6))
plt.bar(categories, values, color=['#FF6100', '#04A0D3', '#92B522'])
plt.title('Srovnání přestupních částek: sezóna 2017-2018')
plt.ylabel('Přestupová částka (mil. $)')
plt.show()